// Westeros battlefield server. Generated by AI for the Claude Code agent-teams dashboard.
// Watches ~/.claude/teams and ~/.claude/tasks plus hook events and streams state over SSE.
const http = require('http');
const fs = require('fs');
const path = require('path');
const os = require('os');

const PORT = Number(process.env.WESTEROS_PORT || 7777);
const HOME = os.homedir();
const TEAMS_DIR = path.join(HOME, '.claude', 'teams');
const TASKS_DIR = path.join(HOME, '.claude', 'tasks');
const RUNTIME = path.join(HOME, '.claude', 'westeros');
const EVENTS_LOG = path.join(RUNTIME, 'events.jsonl');
const ASSETS = path.join(RUNTIME, 'assets');
const INDEX = path.join(__dirname, 'index.html');
const ACTIVE_WINDOW_MS = 6 * 60 * 60 * 1000;

function readJson(file) {
  try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch { return null; }
}

function listTeams() {
  let dirs = [];
  try { dirs = fs.readdirSync(TEAMS_DIR); } catch { return []; }
  return dirs
    .map((name) => {
      const cfg = path.join(TEAMS_DIR, name, 'config.json');
      let mtime = 0;
      try { mtime = fs.statSync(cfg).mtimeMs; } catch { return null; }
      const config = readJson(cfg);
      if (!config) return null;
      return { name, mtime, config };
    })
    .filter(Boolean)
    .sort((a, b) => b.mtime - a.mtime);
}

function readAllEvents() {
  let text = '';
  try { text = fs.readFileSync(EVENTS_LOG, 'utf8'); } catch { return []; }
  const out = [];
  for (const line of text.trim().split('\n').slice(-800)) {
    try { out.push(JSON.parse(line)); } catch {}
  }
  return out;
}

function latestActivityBySession(events) {
  const map = new Map();
  for (const e of events) {
    const sid = e.payload && e.payload.session_id;
    if (!sid) continue;
    const k = sid.slice(0, 8);
    map.set(k, Math.max(map.get(k) || 0, e.ts));
  }
  return map;
}

function pickTeam(requested, events) {
  const teams = listTeams();
  if (requested) {
    const t = teams.find((x) => x.name === requested);
    if (t) return t;
  }
  const activity = latestActivityBySession(events);
  const now = Date.now();
  const scored = teams.map((t) => {
    const sid = t.name.replace(/^session-/, '');
    const mates = (t.config.members || []).length - 1;
    const last = Math.max(t.mtime, activity.get(sid) || 0);
    const recent = now - last < ACTIVE_WINDOW_MS;
    return { t, score: (mates > 0 ? 1e15 : 0) + (recent ? 1e14 : 0) + last };
  });
  scored.sort((a, b) => b.score - a.score);
  return scored.length ? scored[0].t : null;
}

function readTasks(teamName) {
  const dir = path.join(TASKS_DIR, teamName);
  let files = [];
  try { files = fs.readdirSync(dir); } catch { return []; }
  return files
    .filter((f) => f.endsWith('.json'))
    .map((f) => {
      const t = readJson(path.join(dir, f));
      if (!t) return null;
      let mtime = 0;
      try { mtime = fs.statSync(path.join(dir, f)).mtimeMs; } catch {}
      return { ...t, _mtime: mtime };
    })
    .filter(Boolean)
    .sort((a, b) => Number(a.id) - Number(b.id));
}

function buildState(requestedTeam) {
  const events = readAllEvents();
  const team = pickTeam(requestedTeam, events);
  if (!team) return { team: null, members: [], tasks: [], events: [], now: Date.now() };
  const sessionPrefix = team.name.replace(/^session-/, '');
  return {
    team: team.name,
    createdAt: team.config.createdAt,
    members: team.config.members || [],
    tasks: readTasks(team.name),
    events: events.filter((e) => e.payload && String(e.payload.session_id || '').startsWith(sessionPrefix)).slice(-300),
    now: Date.now(),
  };
}

const clients = new Set();
function broadcast() {
  for (const res of clients) {
    const data = JSON.stringify(buildState(res.westerosTeam));
    if (res.lastData === data) continue;
    res.lastData = data;
    res.write(`data: ${data}\n\n`);
  }
}
setInterval(broadcast, 600);

const MIME = { '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png', '.webp': 'image/webp', '.md': 'text/markdown; charset=utf-8', '.svg': 'image/svg+xml' };

const server = http.createServer((req, res) => {
  const url = new URL(req.url, `http://localhost:${PORT}`);
  if (url.pathname === '/') {
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-cache' });
    fs.createReadStream(INDEX).pipe(res);
    return;
  }
  if (url.pathname.startsWith('/assets/')) {
    const file = path.join(ASSETS, path.basename(url.pathname));
    if (!fs.existsSync(file)) { res.writeHead(404); res.end(); return; }
    res.writeHead(200, { 'Content-Type': MIME[path.extname(file)] || 'application/octet-stream', 'Cache-Control': 'max-age=3600' });
    fs.createReadStream(file).pipe(res);
    return;
  }
  if (url.pathname === '/api/state') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(buildState(url.searchParams.get('team'))));
    return;
  }
  if (url.pathname === '/events') {
    res.writeHead(200, { 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache', Connection: 'keep-alive' });
    res.westerosTeam = url.searchParams.get('team') || null;
    res.lastData = JSON.stringify(buildState(res.westerosTeam));
    res.write(`data: ${res.lastData}\n\n`);
    clients.add(res);
    req.on('close', () => clients.delete(res));
    return;
  }
  res.writeHead(404);
  res.end('not found');
});

server.listen(PORT, '127.0.0.1', () => {
  console.log(`Westeros battlefield: http://localhost:${PORT}`);
});
